services:
  postgres:
    image: postgres:16-alpine
    container_name: nightmare-postgres
    environment:
      POSTGRES_DB: nightmare
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - nightmare-postgres-data:/var/lib/postgresql/data

volumes:
  nightmare-postgres-data:
