import Image from "next/image";

export function SpriteStage() {
  return (
    <div className="sprite-stage" aria-hidden="true">
      {/*
        Replace this src with the real downloaded GIF later, for example:
        src="/sprites/ragnarok-character.gif"

        Generated by `npm run sprite:costume` from iRO Costume walk frames.
        To customize it, create scripts/costume-character.json and rerun the script.
      */}
      <Image
        className="walking-footer-sprite pixelated"
        src="/sprites/nightmare-walker.gif"
        alt=""
        width={124}
        height={85}
        unoptimized
      />
    </div>
  );
}
