const fourthJobClassIds = new Set([
  "Hyper_Novice",
  "Dragon_Knight",
  "Dragon_Knight2",
  "Imperial_Guard",
  "Imperial_Guard2",
  "Arch_Mage",
  "Elemental_Master",
  "Windhawk",
  "Windhawk2",
  "Troubadour",
  "Trouvere",
  "Cardinal",
  "Inquisitor",
  "Meister",
  "Meister2",
  "Biolo",
  "Shadow_Cross",
  "Abyss_Chaser",
  "Sky_Emperor",
  "Sky_Emperor2",
  "Soul_Ascetic",
  "Night_Watch",
  "Shinkiro",
  "Shiranui",
  "Spirit_Handler",
]);

const transcendentEquivalentClassIds = new Set([
  "Rune_Knight",
  "Rune_Knight2",
  "Rune_Knight_T",
  "Rune_Knight_T2",
  "Dragon_Knight",
  "Dragon_Knight2",
  "Royal_Guard",
  "Royal_Guard2",
  "Royal_Guard_T",
  "Royal_Guard_T2",
  "Imperial_Guard",
  "Imperial_Guard2",
  "Warlock",
  "Warlock_T",
  "Arch_Mage",
  "Sorcerer",
  "Sorcerer_T",
  "Elemental_Master",
  "Ranger",
  "Ranger2",
  "Ranger_T",
  "Ranger_T2",
  "Windhawk",
  "Windhawk2",
  "Minstrel",
  "Minstrel_T",
  "Troubadour",
  "Wanderer",
  "Wanderer_T",
  "Trouvere",
  "Arch_Bishop",
  "Arch_Bishop_T",
  "Cardinal",
  "Sura",
  "Sura_T",
  "Inquisitor",
  "Mechanic",
  "Mechanic2",
  "Mechanic_T",
  "Mechanic_T2",
  "Meister",
  "Meister2",
  "Genetic",
  "Genetic_T",
  "Biolo",
  "Guillotine_Cross",
  "Guillotine_Cross_T",
  "Shadow_Cross",
  "Shadow_Chaser",
  "Shadow_Chaser_T",
  "Abyss_Chaser",
]);

export function isFourthJobClassId(classId: string) {
  return fourthJobClassIds.has(classId);
}

export function isTranscendentEquivalentClassId(classId: string) {
  return transcendentEquivalentClassIds.has(classId);
}
