import type { JobStatBonusGroup } from "./job-stat-bonuses.types";

export const jobStatBonusGroups: JobStatBonusGroup[] = [
  {
    classIds: ["Swordman", "Swordman_High", "Baby_Swordman"],
    bonuses: [
      { level: 2, str: 1 },
      { level: 6, vit: 1 },
      { level: 10, dex: 1 },
      { level: 14, str: 1 },
      { level: 18, vit: 1 },
      { level: 22, dex: 1 },
      { level: 26, luk: 1 },
      { level: 30, agi: 1 },
      { level: 33, str: 1 },
      { level: 36, dex: 1 },
      { level: 38, vit: 1 },
      { level: 40, str: 1 },
      { level: 42, vit: 1 },
      { level: 44, luk: 1 },
      { level: 46, agi: 1 },
    ],
  },
  {
    classIds: ["Knight", "Knight2", "Baby_Knight", "Baby_Knight2"],
    bonuses: [
      { level: 1, vit: 1 },
      { level: 3, vit: 1 },
      { level: 4, str: 1 },
      { level: 5, luk: 1 },
      { level: 8, vit: 1 },
      { level: 10, str: 1 },
      { level: 11, dex: 1 },
      { level: 12, vit: 1 },
      { level: 13, agi: 1 },
      { level: 15, str: 1 },
      { level: 17, vit: 1 },
      { level: 18, vit: 1 },
      { level: 19, dex: 1 },
      { level: 20, luk: 1 },
      { level: 21, str: 1 },
    ],
  },
  {
    classIds: ["Dragon_Knight", "Dragon_Knight2"],
    bonuses: [
      { level: 1, str: 1, pow: 1 },
      { level: 2, dex: 1, spl: 1 },
      { level: 3, agi: 1, crt: 1 },
      { level: 4, dex: 1 },
      { level: 5, agi: 1, vit: 1, con: 1 },
      { level: 7, luk: 1, spl: 1 },
      { level: 8, int: 1, sta: 1 },
      { level: 9, str: 1, crt: 1 },
      { level: 10, dex: 1 },
      { level: 11, int: 1 },
    ],
  },
];
